#ifndef CARD_TYPE_H_
# define CARD_TYPE_H_

# define CTYPE_ROMONLY                     (0x00)
# define CTYPE_MBC1                        (0x01)
# define CTYPE_MBC1RAM                     (0x02)
# define CTYPE_MBC1RAMBATTERY              (0x03)
# define CTYPE_MBC2                        (0x05)
# define CTYPE_MBC2BATTERY                 (0x06)
# define CTYPE_ROMRAM                      (0x08)
# define CTYPE_ROMRAMBATTERY               (0x09)
# define CTYPE_MMM01                       (0x0B)
# define CTYPE_MMM01RAM                    (0x0C)
# define CTYPE_MMM01RAMBATTERY             (0x0D)
# define CTYPE_MBC3TIMERBATTERY            (0x0F)
# define CTYPE_MBC3TIMBERRAMBATTERY        (0x10)
# define CTYPE_MBC3                        (0x11)
# define CTYPE_MBC3RAM                     (0x12)
# define CTYPE_MBC3RAMBATTERY              (0x13)
# define CTYPE_MBC5                        (0x19)
# define CTYPE_MBC5RAM                     (0x1A)
# define CTYPE_MBC5RAMBATTERY              (0x1B)
# define CTYPE_MBC5RUMBLE                  (0x1C)
# define CTYPE_MBC5RUMBLERAM               (0x1D)
# define CTYPE_MBC5RUMBLERAMBATTERY        (0x1E)
# define CTYPE_MBC6                        (0x20)
# define CTYPE_MBC7SENSORRUMBLERAMBATTERY  (0x22)
# define CTYPE_POCKETCAMERA                (0xFC)
# define CTYPE_BANDAITAMA5                 (0xFD)
# define CTYPE_HUC3                        (0xFE)
# define CTYPE_HUCRAMBATTERY               (0xFF)

#endif /* !CARD_TYPE_H_ */
